always fail examples on error

diff --git a/.github/workflows/check-releasability.yml b/.github/workflows/check-releasability.yml
--- a/.github/workflows/check-releasability.yml
+++ b/.github/workflows/check-releasability.yml
@@ -332,22 +332,22 @@ jobs:
           DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libx264-164 libx264-dev
       - name: Document with scrapping example
         id: scrape
-        continue-on-error: true
+        # continue-on-error: true
         run: |
           cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples --no-deps --all-features
-      - name: Fail when needed
-        run: |
-          if [[ ${{ steps.initial.outputs.initial }} == "false" ]]; then
-            if [[ "${{ steps.scrape.outcome }}" == "success" ]]; then
-              echo "Failure expected but succeeded"
-              exit 2
-            fi
-          else
-            if [[ "${{ steps.scrape.outcome }}" == "failure" ]]; then
-              echo "Success expected but failed"
-              exit 1
-            fi
-          fi
+      # - name: Fail when needed
+      #   run: |
+      #     if [[ ${{ steps.initial.outputs.initial }} == "false" ]]; then
+      #       if [[ "${{ steps.scrape.outcome }}" == "success" ]]; then
+      #         echo "Failure expected but succeeded"
+      #         exit 2
+      #       fi
+      #     else
+      #       if [[ "${{ steps.scrape.outcome }}" == "failure" ]]; then
+      #         echo "Success expected but failed"
+      #         exit 1
+      #       fi
+      #     fi
 
   example-doc-check2:
     name: Example Documentation
@@ -388,22 +388,22 @@ jobs:
           DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libx264-164 libx264-dev
       - name: Document with scrapping example
         id: scrape
-        continue-on-error: true
+        # continue-on-error: true
         run: |
           cargo +nightly doc -Zunstable-options -Zrustdoc-scrape-examples --no-deps --all-features
-      - name: Fail when needed
-        run: |
-          if [[ ${{ steps.initial.outputs.initial }} == "false" ]]; then
-            if [[ "${{ steps.scrape.outcome }}" == "success" ]]; then
-              echo "Failure expected but succeeded"
-              exit 2
-            fi
-          else
-            if [[ "${{ steps.scrape.outcome }}" == "failure" ]]; then
-              echo "Success expected but failed"
-              exit 1
-            fi
-          fi
+      # - name: Fail when needed
+      #   run: |
+      #     if [[ ${{ steps.initial.outputs.initial }} == "false" ]]; then
+      #       if [[ "${{ steps.scrape.outcome }}" == "success" ]]; then
+      #         echo "Failure expected but succeeded"
+      #         exit 2
+      #       fi
+      #     else
+      #       if [[ "${{ steps.scrape.outcome }}" == "failure" ]]; then
+      #         echo "Success expected but failed"
+      #         exit 1
+      #       fi
+      #     fi
 
   release-private-registry:
     name: Release to Private Registry
